runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build
env_variables:
  SENDGRID_API_KEY: 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
